### ISSUE TITLE
using the random seed of FsCheck

### ISSUE THREAD

**Issue by giacomociti** [moodmosaic/FsCheck.Regex#1]
The output printed by the following snippet should be deterministic, because we are passing in the random seed of FsCheck:

```
let arb = Arb.fromGen (matching "[xX][0-9a-z]")
let prop = Prop.forAll arb (fun x -> x.StartsWith "x")
let cfg = { Config.Default with MaxTest = 1; Replay = Some(Random.StdGen(1490369583,296202216)) }
Check.One(cfg, prop)
```

but it's not deterministic since Fare uses it's own random generation (based on BCL  Random).
If Fare accepted a custom random generator, we could somehow inject the one from FSCheck.

**Comment by moodmosaic** [comment]
Great suggestion :smiley: To be honest, I'm not entirely sure how trivial it would be to implement  this in [Fare](https://github.com/moodmosaic/Fare).

This looks more like an issue for Fare though, so we should probably close this one and open it as a new issue in Fare...

**Comment by giacomociti** [comment]
I'm closing this because you're right, this is more like an issue for Fare.
I've been tinkering about it [a while ago](http://stackoverflow.com/questions/32864143/turning-a-generator-based-on-system-random-into-an-fscheck-generator) but the problem is not trivial at all.
